name: Build plugin
on:
  push:
    tags:
      - '*'
env:
  PLUGIN_NAME: logseq-catppuccin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x' # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm i && npm run build # sass -> css
          mkdir ${{ env.PLUGIN_NAME }} # folder for zip
          mkdir ${{ env.PLUGIN_NAME }}/assets # folder for icon
          cp assets/icon.png ${{ env.PLUGIN_NAME }}/assets # move icon
          cp README.md package.json index.html index.js ctp-latte.css ctp-frappe.css ctp-macchiato.css ctp-mocha.css ctp-oled.css ${{ env.PLUGIN_NAME }} # move build assets
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref }}.zip ${{ env.PLUGIN_NAME }} # create zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with: 
          draft: true
          files: |
            package.json
            ${{ env.PLUGIN_NAME }}-${{ github.ref }}.zip
            ctp-latte.css
            ctp-frappe.css
            ctp-macchiato.css
            ctp-mocha.css
            ctp-oled.css
